### ISSUE TITLE
データベースの実装

### ISSUE THREAD

**Issue by punipuni21** [yusuke-suehiro/ScheduleSubmit#1]
- xamppとMySQLを使うのはどうですか？

以下，参考までに
https://unsolublesugar.com/20130419/050518/
https://qiita.com/miriwo/items/37e4dfec4484d389db07

**Comment by yusuke-suehiro** [comment]
今はxamppは使っていないんですが，phpとapacheとMySQLを使っています．
ちょっとpdfは難しそうなので，まずphpで受け取ったtextやcheckboxの値などをMySQLに保存するというものを作成しました．(ShiftConfirmation)
xamppについてはあまり詳しく知らないので調べてみようと思います．
ありがとうございます．
