### ISSUE TITLE
サーバについて

### ISSUE THREAD

**Issue by punipuni21** [yusuke-suehiro/ScheduleSubmit#2]
レンタルサーバとかを借りてたりしますか？

借りてない場合は無料のレンタルサーバを借りて開発してみたいなと思っているのですが

**Comment by yusuke-suehiro** [comment]
借りてないです

ある程度のところまで完成したら借りてみようかなあと考えていました

**Comment by punipuni21** [comment]
OK．pdfのデータベース保存はこちらでも検討してみます
